sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install flake8
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 --max-line-length=100 datadog; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python setup.py test; else python setup.py test -s tests.unit; fi
